### ISSUE TITLE
表とそのタイトルがページをまたがって表示されることがある

### ISSUE THREAD

**Issue by shimozawa-takahiro** [mitsuyukiLab/grad_thesis_typst#11]
表とそのタイトルがページをまたがって表示されています。図でも発生しています。

**Comment by taiga4112** [comment]
@shimozawa-takahiro こちら、以下の例のように、`placement: none`を標準としていますが、
`auto`などに変更してもこの現象は発生しますか？

解決するのであれば、`none`を使わないことで対応するという方針になります

```typst
#figure(
  image("img/example.svg", width: 90%),
  placement: none, // top, bottom, auto, none
  caption: "Example of a figure.",
  supplement: "Fig.",
  kind: "image",
) <fig:fig_example>
```

**Comment by shimozawa-takahiro** [comment]
<img width="1920" alt="スクリーンショット 2024-10-25 15 54 45" src="https://github.com/user-attachments/assets/3b31b86f-b709-4282-be6f-9e3a64dc8059">
Placementをautoにしても発生しています。
