### ISSUE TITLE
文中に数式を組み込むと、番号付き数式の番号そのものが変な値になる

### ISSUE THREAD

**Issue by Haruki-Yama** [mitsuyukiLab/grad_thesis_typst#7]
文中に記載する数式が、番号を付与する数式より前にある場合、数式番号が◯.1からにならないです。
現状、第3章において数式番号を付けたい数式の前に、文中の数式が12個あるため、初めの数式が3.13になります。
その前に文中の数式を増やすと3.14と増えていきます。

文中とブロックでの数式の表記方法が異なるのか調べています。
また、あまり深くまで調べられていませんが、grad_thesis_ib.typでのCounting equation numberが表番号と図番号の数え方と同じところに原因があるのかなと思っています。

**Comment by taiga4112** [comment]
> 文中の数式が12個あるため、初めの数式が3.13になります。
その前に文中の数式を増やすと3.14と増えていきます。

このことから、単に文中の数式もnumberingされているということになりますね。

**Comment by taiga4112** [comment]
[これ](https://qiita.com/tomoyatajika/items/bf52a066874f7370c77a#%E5%BC%8F%E3%82%92%E5%BC%95%E7%94%A8%E3%81%97%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%A0%E3%81%91%E6%95%B0%E5%BC%8F%E7%95%AA%E5%8F%B7%E3%82%92%E3%81%A4%E3%81%91%E3%82%8B)のように、引用したら数式番号をつける方法もあるようです。

これをうまくライブラリ化しようとしている（？）ものも発見。
https://github.com/Ttajika/auto-ref-numbery

**Comment by taiga4112** [comment]
[これ](https://github.com/typst/typst/issues/362)の逆向き解決がスマートそうに思える
